// Code generated by go-queryset. DO NOT EDIT.
package storage

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// ===== BEGIN of all query sets

// ===== BEGIN of query set gormStorageMsgQuerySet

// gormStorageMsgQuerySet is an queryset type for gormStorageMsg
type gormStorageMsgQuerySet struct {
	db *gorm.DB
}

// NewgormStorageMsgQuerySet constructs new gormStorageMsgQuerySet
func NewgormStorageMsgQuerySet(db *gorm.DB) gormStorageMsgQuerySet {
	return gormStorageMsgQuerySet{
		db: db.Model(&gormStorageMsg{}),
	}
}

func (qs gormStorageMsgQuerySet) w(db *gorm.DB) gormStorageMsgQuerySet {
	return NewgormStorageMsgQuerySet(db)
}

func (qs gormStorageMsgQuerySet) With(callback func(db *gorm.DB) *gorm.DB) gormStorageMsgQuerySet {
	return qs.w(callback(qs.db))
}

func (qs gormStorageMsgQuerySet) Select(fields ...gormStorageMsgDBSchemaField) gormStorageMsgQuerySet {
	names := []string{}
	for _, f := range fields {
		names = append(names, f.String())
	}

	return qs.w(qs.db.Select(strings.Join(names, ",")))
}

// Create is an autogenerated method
// nolint: dupl
func (o *gormStorageMsg) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *gormStorageMsg) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// All is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) All(ret *[]*gormStorageMsg) error {
	return qs.db.Find(ret).Error
}

// Count is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) Count() (int64, error) {
	var count int64
	err := qs.db.Count(&count).Error
	return count, err
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) CreatedAtEq(createdAt time.Time) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("created_at = ?", createdAt))
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) CreatedAtGt(createdAt time.Time) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("created_at > ?", createdAt))
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) CreatedAtGte(createdAt time.Time) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("created_at >= ?", createdAt))
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) CreatedAtLt(createdAt time.Time) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("created_at < ?", createdAt))
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) CreatedAtLte(createdAt time.Time) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("created_at <= ?", createdAt))
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) CreatedAtNe(createdAt time.Time) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("created_at != ?", createdAt))
}

// Delete is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) Delete() error {
	return qs.db.Delete(&gormStorageMsg{}).Error
}

// DeleteNum is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) DeleteNum() (int64, error) {
	db := qs.db.Delete(&gormStorageMsg{})
	return db.RowsAffected, db.Error
}

// DeleteNumUnscoped is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) DeleteNumUnscoped() (int64, error) {
	db := qs.db.Unscoped().Delete(&gormStorageMsg{})
	return db.RowsAffected, db.Error
}

// FailReasonEq is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) FailReasonEq(failReason string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("fail_reason = ?", failReason))
}

// FailReasonEqP is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) FailReasonEqP(failReason *string) gormStorageMsgQuerySet {
	if failReason == nil {
		return qs.FailReasonIsNull()
	} else {
		return qs.FailReasonEq(*failReason)
	}
}

// FailReasonGt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) FailReasonGt(failReason string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("fail_reason > ?", failReason))
}

// FailReasonGte is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) FailReasonGte(failReason string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("fail_reason >= ?", failReason))
}

// FailReasonIn is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) FailReasonIn(failReason ...string) gormStorageMsgQuerySet {
	if len(failReason) == 0 {
		qs.db.AddError(errors.New("must at least pass one failReason in FailReasonIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("fail_reason IN (?)", failReason))
}

// FailReasonIsNotNull is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) FailReasonIsNotNull() gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("fail_reason IS NOT NULL"))
}

// FailReasonIsNull is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) FailReasonIsNull() gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("fail_reason IS NULL"))
}

// FailReasonLike is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) FailReasonLike(failReason string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("fail_reason LIKE ?", failReason))
}

// FailReasonLt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) FailReasonLt(failReason string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("fail_reason < ?", failReason))
}

// FailReasonLte is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) FailReasonLte(failReason string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("fail_reason <= ?", failReason))
}

// FailReasonNe is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) FailReasonNe(failReason string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("fail_reason != ?", failReason))
}

// FailReasonNotIn is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) FailReasonNotIn(failReason ...string) gormStorageMsgQuerySet {
	if len(failReason) == 0 {
		qs.db.AddError(errors.New("must at least pass one failReason in FailReasonNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("fail_reason NOT IN (?)", failReason))
}

// FailReasonNotlike is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) FailReasonNotlike(failReason string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("fail_reason NOT LIKE ?", failReason))
}

// GetDB is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) GetDB() *gorm.DB {
	return qs.db
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) GetUpdater() gormStorageMsgUpdater {
	return NewgormStorageMsgUpdater(qs.db)
}

// IdEq is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) IdEq(id int64) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("id = ?", id))
}

// IdGt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) IdGt(id int64) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("id > ?", id))
}

// IdGte is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) IdGte(id int64) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("id >= ?", id))
}

// IdIn is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) IdIn(id ...int64) gormStorageMsgQuerySet {
	if len(id) == 0 {
		qs.db.AddError(errors.New("must at least pass one id in IdIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id IN (?)", id))
}

// IdLt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) IdLt(id int64) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("id < ?", id))
}

// IdLte is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) IdLte(id int64) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("id <= ?", id))
}

// IdNe is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) IdNe(id int64) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("id != ?", id))
}

// IdNotIn is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) IdNotIn(id ...int64) gormStorageMsgQuerySet {
	if len(id) == 0 {
		qs.db.AddError(errors.New("must at least pass one id in IdNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id NOT IN (?)", id))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) Limit(limit int) gormStorageMsgQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// MessageEq is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MessageEq(message datatypes.JSON) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("message = ?", message))
}

// MessageIn is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MessageIn(message ...datatypes.JSON) gormStorageMsgQuerySet {
	if len(message) == 0 {
		qs.db.AddError(errors.New("must at least pass one message in MessageIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("message IN (?)", message))
}

// MessageNe is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MessageNe(message datatypes.JSON) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("message != ?", message))
}

// MessageNotIn is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MessageNotIn(message ...datatypes.JSON) gormStorageMsgQuerySet {
	if len(message) == 0 {
		qs.db.AddError(errors.New("must at least pass one message in MessageNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("message NOT IN (?)", message))
}

// MqClientNameEq is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MqClientNameEq(mqClientName string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("mq_client_name = ?", mqClientName))
}

// MqClientNameGt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MqClientNameGt(mqClientName string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("mq_client_name > ?", mqClientName))
}

// MqClientNameGte is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MqClientNameGte(mqClientName string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("mq_client_name >= ?", mqClientName))
}

// MqClientNameIn is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MqClientNameIn(mqClientName ...string) gormStorageMsgQuerySet {
	if len(mqClientName) == 0 {
		qs.db.AddError(errors.New("must at least pass one mqClientName in MqClientNameIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("mq_client_name IN (?)", mqClientName))
}

// MqClientNameLike is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MqClientNameLike(mqClientName string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("mq_client_name LIKE ?", mqClientName))
}

// MqClientNameLt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MqClientNameLt(mqClientName string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("mq_client_name < ?", mqClientName))
}

// MqClientNameLte is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MqClientNameLte(mqClientName string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("mq_client_name <= ?", mqClientName))
}

// MqClientNameNe is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MqClientNameNe(mqClientName string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("mq_client_name != ?", mqClientName))
}

// MqClientNameNotIn is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MqClientNameNotIn(mqClientName ...string) gormStorageMsgQuerySet {
	if len(mqClientName) == 0 {
		qs.db.AddError(errors.New("must at least pass one mqClientName in MqClientNameNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("mq_client_name NOT IN (?)", mqClientName))
}

// MqClientNameNotlike is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) MqClientNameNotlike(mqClientName string) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("mq_client_name NOT LIKE ?", mqClientName))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) Offset(offset int) gormStorageMsgQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs gormStorageMsgQuerySet) One(ret *gormStorageMsg) error {
	return qs.db.First(ret).Error
}

// OrderAscByCreatedAt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderAscByCreatedAt() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("created_at ASC"))
}

// OrderAscByFailReason is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderAscByFailReason() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("fail_reason ASC"))
}

// OrderAscById is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderAscById() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscByMessage is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderAscByMessage() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("message ASC"))
}

// OrderAscByMqClientName is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderAscByMqClientName() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("mq_client_name ASC"))
}

// OrderAscByStatus is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderAscByStatus() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("status ASC"))
}

// OrderAscByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderAscByUpdatedAt() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("updated_at ASC"))
}

// OrderDescByCreatedAt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderDescByCreatedAt() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("created_at DESC"))
}

// OrderDescByFailReason is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderDescByFailReason() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("fail_reason DESC"))
}

// OrderDescById is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderDescById() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescByMessage is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderDescByMessage() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("message DESC"))
}

// OrderDescByMqClientName is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderDescByMqClientName() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("mq_client_name DESC"))
}

// OrderDescByStatus is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderDescByStatus() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("status DESC"))
}

// OrderDescByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) OrderDescByUpdatedAt() gormStorageMsgQuerySet {
	return qs.w(qs.db.Order("updated_at DESC"))
}

// StatusEq is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) StatusEq(status int) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("status = ?", status))
}

// StatusGt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) StatusGt(status int) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("status > ?", status))
}

// StatusGte is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) StatusGte(status int) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("status >= ?", status))
}

// StatusIn is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) StatusIn(status ...int) gormStorageMsgQuerySet {
	if len(status) == 0 {
		qs.db.AddError(errors.New("must at least pass one status in StatusIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("status IN (?)", status))
}

// StatusLt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) StatusLt(status int) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("status < ?", status))
}

// StatusLte is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) StatusLte(status int) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("status <= ?", status))
}

// StatusNe is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) StatusNe(status int) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("status != ?", status))
}

// StatusNotIn is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) StatusNotIn(status ...int) gormStorageMsgQuerySet {
	if len(status) == 0 {
		qs.db.AddError(errors.New("must at least pass one status in StatusNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("status NOT IN (?)", status))
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) UpdatedAtEq(updatedAt time.Time) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("updated_at = ?", updatedAt))
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) UpdatedAtGt(updatedAt time.Time) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("updated_at > ?", updatedAt))
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) UpdatedAtGte(updatedAt time.Time) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("updated_at >= ?", updatedAt))
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) UpdatedAtLt(updatedAt time.Time) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("updated_at < ?", updatedAt))
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) UpdatedAtLte(updatedAt time.Time) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("updated_at <= ?", updatedAt))
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs gormStorageMsgQuerySet) UpdatedAtNe(updatedAt time.Time) gormStorageMsgQuerySet {
	return qs.w(qs.db.Where("updated_at != ?", updatedAt))
}

// IncCreatedAt is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) IncCreatedAt(createdAt time.Time) gormStorageMsgUpdater {
	u.fields[string(gormStorageMsgDBSchema.CreatedAt)] = gorm.Expr(string(gormStorageMsgDBSchema.CreatedAt)+" + ?", createdAt)
	return u
}

// IncId is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) IncId(id int64) gormStorageMsgUpdater {
	u.fields[string(gormStorageMsgDBSchema.Id)] = gorm.Expr(string(gormStorageMsgDBSchema.Id)+" + ?", id)
	return u
}

// IncStatus is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) IncStatus(status int) gormStorageMsgUpdater {
	u.fields[string(gormStorageMsgDBSchema.Status)] = gorm.Expr(string(gormStorageMsgDBSchema.Status)+" + ?", status)
	return u
}

// IncUpdatedAt is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) IncUpdatedAt(updatedAt time.Time) gormStorageMsgUpdater {
	u.fields[string(gormStorageMsgDBSchema.UpdatedAt)] = gorm.Expr(string(gormStorageMsgDBSchema.UpdatedAt)+" + ?", updatedAt)
	return u
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) SetCreatedAt(createdAt time.Time) gormStorageMsgUpdater {
	u.fields[string(gormStorageMsgDBSchema.CreatedAt)] = createdAt
	return u
}

// SetFailReason is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) SetFailReason(failReason *string) gormStorageMsgUpdater {
	u.fields[string(gormStorageMsgDBSchema.FailReason)] = failReason
	return u
}

// SetId is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) SetId(id int64) gormStorageMsgUpdater {
	u.fields[string(gormStorageMsgDBSchema.Id)] = id
	return u
}

// SetMessage is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) SetMessage(message datatypes.JSON) gormStorageMsgUpdater {
	u.fields[string(gormStorageMsgDBSchema.Message)] = message
	return u
}

// SetMqClientName is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) SetMqClientName(mqClientName string) gormStorageMsgUpdater {
	u.fields[string(gormStorageMsgDBSchema.MqClientName)] = mqClientName
	return u
}

// SetStatus is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) SetStatus(status int) gormStorageMsgUpdater {
	u.fields[string(gormStorageMsgDBSchema.Status)] = status
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) SetUpdatedAt(updatedAt time.Time) gormStorageMsgUpdater {
	u.fields[string(gormStorageMsgDBSchema.UpdatedAt)] = updatedAt
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// With is an autogenerated method
// nolint: dupl
func (u gormStorageMsgUpdater) With(callback func(fields map[string]interface{}) map[string]interface{}) gormStorageMsgUpdater {
	u.fields = callback(u.fields)
	return u
}

// ===== END of query set gormStorageMsgQuerySet

// ===== BEGIN of gormStorageMsg modifiers

// gormStorageMsgDBSchemaField describes database schema field. It requires for method 'Update'
type gormStorageMsgDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f gormStorageMsgDBSchemaField) String() string {
	return string(f)
}

// gormStorageMsgDBSchema stores db field names of gormStorageMsg
var gormStorageMsgDBSchema = struct {
	Id           gormStorageMsgDBSchemaField
	CreatedAt    gormStorageMsgDBSchemaField
	UpdatedAt    gormStorageMsgDBSchemaField
	MqClientName gormStorageMsgDBSchemaField
	Message      gormStorageMsgDBSchemaField
	Status       gormStorageMsgDBSchemaField
	FailReason   gormStorageMsgDBSchemaField
}{

	Id:           gormStorageMsgDBSchemaField("id"),
	CreatedAt:    gormStorageMsgDBSchemaField("created_at"),
	UpdatedAt:    gormStorageMsgDBSchemaField("updated_at"),
	MqClientName: gormStorageMsgDBSchemaField("mq_client_name"),
	Message:      gormStorageMsgDBSchemaField("message"),
	Status:       gormStorageMsgDBSchemaField("status"),
	FailReason:   gormStorageMsgDBSchemaField("fail_reason"),
}

// Update updates gormStorageMsg fields by primary key
// nolint: dupl
func (o *gormStorageMsg) Update(db *gorm.DB, fields ...gormStorageMsgDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":             o.Id,
		"created_at":     o.CreatedAt,
		"updated_at":     o.UpdatedAt,
		"mq_client_name": o.MqClientName,
		"message":        o.Message,
		"status":         o.Status,
		"fail_reason":    o.FailReason,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update gormStorageMsg %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// gormStorageMsgUpdater is an gormStorageMsg updates manager
type gormStorageMsgUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewgormStorageMsgUpdater creates new gormStorageMsg updater
// nolint: dupl
func NewgormStorageMsgUpdater(db *gorm.DB) gormStorageMsgUpdater {
	return gormStorageMsgUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&gormStorageMsg{}),
	}
}

// ===== END of gormStorageMsg modifiers

// ===== END of all query sets
